# Generated by Django 5.1.6 on 2025-05-02 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0002_employee_role_alter_myuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(default=9900, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsapp.department')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='designation_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='imsapp.designation'),
            preserve_default=False,
        ),
    ]
