# Generated by Django 5.1.6 on 2025-05-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0003_department_employee_job_title_employee_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
