# Generated by Django 5.1.6 on 2025-05-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0004_alter_myuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='dep_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imsapp.department'),
        ),
    ]
