# Generated by Django 5.1.6 on 2025-05-14 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0005_alter_designation_dep_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='imsapp.designation'),
        ),
    ]
