# Generated by Django 5.1.6 on 2025-05-15 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0006_alter_employee_designation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributingFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentPOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poc', to='imsapp.department')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deps', to='imsapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=600)),
                ('risk_level', models.CharField(blank=True, max_length=200, null=True)),
                ('assigned_poc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsapp.departmentpoc')),
                ('contributing_factor', models.ManyToManyField(db_table='IncidentFactor', to='imsapp.contributingfactor')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsapp.department')),
                ('requestor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsapp.employee')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsapp.incidenttype')),
            ],
        ),
    ]
