# Generated by Django 5.1.6 on 2025-05-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0007_contributingfactor_departmentpoc_incidenttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentticket',
            name='description',
        ),
    ]
