# Generated by Django 5.1.6 on 2025-03-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0002_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='carousal/')),
                ('files', models.FileField(upload_to='File/')),
            ],
        ),
    ]
