# Generated by Django 5.1.6 on 2025-03-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0003_carousal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousal',
            name='files',
            field=models.FileField(upload_to=''),
        ),
    ]
